import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "build/main.js",
});

if (prod) {
	// Read current version from manifest.json (already synced by version-bump.mjs)
	const manifestPath = "manifest.json";
	const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
	console.log(`✓ Building version ${manifest.version}`);

	// Build with current version
	await context.rebuild();

	// Copy to Obsidian plugins folder
	const pluginFolder = "/Users/jeroendezwart/2th Brain/.obsidian/plugins/pdf-export";
	fs.copyFileSync("build/main.js", `${pluginFolder}/main.js`);
	fs.copyFileSync(manifestPath, `${pluginFolder}/manifest.json`);
	console.log(`✓ Copied build/main.js and manifest.json to ${pluginFolder}`);
	console.log(`✓ Plugin version: ${manifest.version}`);

	process.exit(0);
} else {
	await context.watch();
}
